import { StyleSheet } from "react-native";

import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 32 },
  eyebrow: {
    ...typography.medium,
    color: colors.accent,
    fontSize: 11,
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  title: { ...typography.semiBold, color: colors.text, fontSize: 27, marginBottom: 18 },
  profileCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    padding: 14,
  },
  avatar: {
    ...typography.semiBold,
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 22,
    color: colors.text,
    fontSize: 18,
    height: 44,
    justifyContent: "center",
    textAlign: "center",
    textAlignVertical: "center",
    width: 44,
  },
  profileText: { flex: 1, marginLeft: 12 },
  profileName: { ...typography.semiBold, color: colors.text, fontSize: 14 },
  profileEmail: { ...typography.regular, color: colors.textSecondary, fontSize: 12, marginTop: 3 },
  edit: { ...typography.medium, color: colors.primary, fontSize: 12 },
  sectionLabel: {
    ...typography.medium,
    color: colors.textSecondary,
    fontSize: 10,
    letterSpacing: 0.75,
    marginBottom: 9,
    marginLeft: 4,
    marginTop: 22,
  },
  group: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 15,
    borderWidth: 1,
    overflow: "hidden",
  },
  publishParking: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", minHeight: 61, paddingHorizontal: 14 },
  row: { alignItems: "center", flexDirection: "row", minHeight: 61, paddingHorizontal: 14 },
  rowBorder: { borderBottomColor: colors.border, borderBottomWidth: 1 },
  rowText: { flex: 1 },
  rowTitle: { ...typography.medium, color: colors.text, fontSize: 14 },
  rowSubtitle: { ...typography.regular, color: colors.textSecondary, fontSize: 11, marginTop: 3 },
  rowValue: { ...typography.medium, color: colors.primary, fontSize: 13, marginRight: 5 },
  toggle: { backgroundColor: colors.primary, borderRadius: 14, height: 25, padding: 3, width: 46 },
  toggleKnob: { alignSelf: "flex-end", backgroundColor: colors.text, borderRadius: 10, height: 19, width: 19 },
  logout: { alignItems: "center", flexDirection: "row", justifyContent: "center", minHeight: 54 },
  logoutText: { ...typography.medium, color: colors.danger, fontSize: 14, marginLeft: 8 },
});
